SELECT * FROM USERINFO;

SELECT * FROM ROLE;

SELECT * FROM USERINFO_ROLE;

SELECT * FROM FUNCTION;

SELECT * FROM ROLE_FUNCTION;

SELECT * FROM MODULE;

SELECT * FROM USERINFO;

SELECT * FROM USERINFO;